### PR TITLE
fix: Update to adonis v5 release, bullmq 1.24 and bull-board to 2.0.3

### PR DESCRIPTION
**Pull request by arthur-er**
**Changes proposed**
Update Adonis to v5 release (5.1.6)

The current behavior is the usage of the old container bindings of adonis preview release as seen on https://github.com/Rocketseat/adonis-bull/issues/79

The new behavior is the usage of updated bindings

### CODE REVIEW

**Comment by arthur-er** [comment]
I have no clue on how to update the invoke/configure command which is not working ATM.

**Comment by jdkdev** [comment]
Thanks Arthur for doing that. I hope this can be merged soon!

**Comment by Bilusca** [comment]
Thanks @arthur-er :+1:

**Comment by SandroReis** [comment]
Thanks Arthur for doing that. I need this fix too and i hope this can be merged soon!

**Comment by HigoRibeiro** [comment]
Thanks @arthur-er for your contrib!! 

I'll see this today!! 🚀

**Review by HigoRibeiro — APPROVED** [review]
Great work here @arthur-er !! 🚀

**Comment by lamtabonebrand** [comment]
Great! Thank you!

**Pull request merged**
